### ISSUE TITLE
Invalid API key!

### ISSUE THREAD

**Issue by AlbertoN97** [Julynx/wthr#1]
Hi, I just created an api key to use it on the program but it said its invalid. Is it because it isn't syncronized yet with openweatherapp yet? Thanks for your app, btw. Pretty cool work.

**Comment by Julynx** [comment]
It may be... Try creating a file inside `~/.config/wthr/` called 'api_key' with no extensions and type out the API key in a single line and without quotes. Also dont add any empty lines above or below it, just the key.

Make sure to set the right permissions for that file and wipe out your current key if you wrote it in the source code by replacing it with "YOUR_API_KEY_HERE" and running the app again.

Also make sure you are running on the latest commit. If the issue persists then regenerate your api key or contact openweathermap for support.

Feel free to reply if this doesnt work in 24 hours and I will re open the issue and look into it more closely :)
